config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#home'

  get '/home', to: 'application#home', as: 'home'
  get '/secret', to: 'application#secret', as: 'secret'
  get '/about', to: 'application#about', as: 'about'
  get '/contact', to: 'application#contact', as: 'contact'

  resources :corporates
  resources :sites
  resources :plants
  resources :lines
  resources :assets
  resources :tags


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :line
  has_many :tags

  validates :name, presence: true
  validates :line_id, presence: true
end

app/models/corporate.rb
class Corporate < ApplicationRecord
  belongs_to :license_package
  has_many :sites

  validates :name, presence: true
  validates :license_package_id, presence: true
end

app/models/license_package.rb
class LicensePackage < ApplicationRecord
	has_one :corporate
	before_create :set_default_package

	validates :name, presence: true

private
  def set_default_package
    self.role ||= LicensePackage.find_by_name('lite')
  end
end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :plant
  has_many :assets

  validates :name, presence: true
  validates :plant_id, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :site
  has_many :lines

  validates :name, presence: true
  validates :site_id, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :corporate
  has_many :plants

  validates :name, presence: true
  validates :corporate_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :asset

  	validates :name, presence: true
  	validates :asset_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  before_create :set_default_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, uniqueness: { case_sensitive: false }, presence: true, allow_blank: false, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

  def generate_jwt
  	JWT.encode({ id: id, exp: 60.days.from_now.to_i }, Rails.application.secrets.secret_key_base)
  end

  private
  def set_default_role
    self.role ||= Role.find_by_name('guest')
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
	def new
  	end

def edit
  @asset = Asset.find(params[:id])
end

def create
   	# render plain: asset_params.inspect
    @asset = Asset.new(asset_params)
    if @asset.save
      flash[:notice] = "You Signed up successfully"
      # flash[:color]= "valid"
    else
      flash[:error] = "Form is invalid"
      # flash[:color]= "invalid"
    end
    redirect_to @asset
   end

   def show
   	@asset = Asset.find(params[:id])
   end

  private

  def asset_params
    params.require(:asset).permit(:name, :line_id)
  end

end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def new
  end

   def create
   	# render plain: plant_params.inspect
    @line = Line.new(line_params)
    if @line.save
      flash[:notice] = "You Signed up successfully"
      # flash[:color]= "valid"
    else
      flash[:error] = "Form is invalid"
      # flash[:color]= "invalid"
    end
    redirect_to @line
   end

   def show
   	@line = Line.find(params[:id])
   end

  private

  def line_params
    params.require(:line).permit(:name, :plant_id)
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def new
  end

   def create
   	# render plain: corporate_params.inspect
    @site = Site.new(:name => site_params["name"], :corporate_id => Corporate.first.id)
    if @site.save
      flash[:notice] = "You Signed up successfully"
      # flash[:color]= "valid"
    else
      flash[:error] = "Form is invalid"
      # flash[:color]= "invalid"
    end
    redirect_to @site
   end

   def show
   	@site = Site.find(params[:id])
   end

  private

  def site_params
    params.require(:site).permit(:name)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
  end

  def index
  	@tags = Tag.all
  end

   def create
   	# render plain: tag_params.inspect
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:notice] = "You Signed up successfully"
      # flash[:color]= "valid"
    else
      flash[:error] = "Form is invalid"
      # flash[:color]= "invalid"
    end
    redirect_to @tag
   end

   def show
   	@tag = Tag.find(params[:id])
   end

  private

  def tag_params
    params.require(:tag).permit(:name, :asset_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/corporates_helper.rb
module CorporatesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <p>#{sentence}</p>
    <ul>#{messages}</ul>
    HTML

    html.html_safe
  end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/assets/edit.html.erb
<h1>Editing asset</h1>
 
<%= form_for :asset, url: asset_path(@asset), method: :patch do |f| %>
 
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@asset.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @asset.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= form.label :choose_line %><br>
    <%= form.select :line_id, Line.all.collect {|c| [ c.name, c.id ] } %><br>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', assets_path %>

app/views/assets/new.html.erb
<%= form_for :asset, url: assets_path, local: true do |form| %>
  
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@asset.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @asset.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :choose_line %><br>
    <%= form.select :line_id, Line.all.collect {|c| [ c.name, c.id ] } %><br>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/assets/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @asset.name %>
</p>
 
<p>
  <strong>Line Name:</strong>
  <%= Line.find(@asset.line_id).name %>
</p>

app/views/lines/edit.html.erb
<h1>Editing line</h1>
 
<%= form_for :line, url: line_path(@line), method: :patch do |f| %>
 
  <% if @line.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@line.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @line.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= form.label :choose_plant %><br>
    <%= form.select :plant_id, Plant.all.collect {|c| [ c.name, c.id ] } %><br>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', lines_path %>

app/views/lines/new.html.erb
<%= form_for :line, url: lines_path, local: true do |form| %>
  
    <% if @line.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@line.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @line.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :choose_plant %><br>
    <%= form.select :plant_id, Plant.all.collect {|c| [ c.name, c.id ] } %><br>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/lines/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @line.name %>
</p>
 
<p>
  <strong>Plant Name:</strong>
  <%= Plant.find(@line.plant_id).name %>
</p>

app/views/sites/edit.html.erb
<h1>Editing site</h1>
 
<%= form_for :site, url: site_path(@site), method: :patch do |f| %>
 
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@site.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @site.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= form.label :choose_corporate %><br>
    <%= form.select :corporate_id, Corporate.all.collect {|c| [ c.name, c.id ] } %><br>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', sites_path %>

app/views/sites/new.html.erb
<%= form_for :site, url: sites_path, local: true do |form| %>

  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@site.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @site.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/sites/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @site.name %>
</p>
 
<p>
  <strong>License Package:</strong>
  <%= Corporate.find(@site.corporate_id).name %>
</p>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>
 
<%= form_for :tag, url: tag_path(@tag), method: :patch do |f| %>
 
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@tag.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @tag.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= form.label :choose_asset %><br>
    <%= form.select :asset_id, Asset.all.collect {|c| [ c.name, c.id ] } %><br>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Asset Name</th>
    <th>Action</th>
  </tr>
 
  <% @tags.each do |tag| %>
    <tr>
      <td><%= tag.name %></td>
      <td><%= Asset.find(tag.asset_id).name %></td>
      <td><%= link_to 'Show', tag_path(tag) %></td>
    </tr>
  <% end %>
</table>

app/views/tags/new.html.erb
<%= form_for :tag, url: tags_path, local: true do |form| %>
  
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@tag.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @tag.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :choose_asset %><br>
    <%= form.select :asset_id, Asset.all.collect {|c| [ c.name, c.id ] } %><br>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/tags/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @tag.name %>
</p>
 
<p>
  <strong>Asset Name:</strong>
  <%= Asset.find(@tag.asset_id).name %>
</p>